# -*- coding: utf-8 -*-
"""Hand-authored ``Ui_MainWindow`` for the File Rename desktop app.

Originally generated by Qt Designer, this module is now the canonical source
of truth for the window layout and styling. It is maintained by hand — do
not regenerate from ``designer/main.ui``.

Every ``setObjectName`` and ``self.*`` widget name below is public API for
``package.views.main_window`` and ``package.views.ui_translator``; keep them
stable when editing.
"""
from __future__ import annotations

from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, QSize, Qt)
from PySide6.QtGui import (QAction, QCursor, QFont, QIcon)
from PySide6.QtWidgets import (
    QAbstractItemView,
    QAbstractScrollArea,
    QCheckBox,
    QComboBox,
    QCommandLinkButton,
    QFrame,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QListView,
    QListWidget,
    QMainWindow,
    QMenu,
    QMenuBar,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSpinBox,
    QSplitter,
    QStatusBar,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)


# ---------------------------------------------------------------------------
# Design tokens — dark navy + restrained orange. Swap these to rebrand.
# ---------------------------------------------------------------------------
_BG_BASE = "#1f2a38"        # deep navy window background
_BG_CARD = "#232f3e"        # slightly lifted card surface
_BG_ELEVATED = "#2a3748"    # inputs, buttons, list rows
_BG_HOVER = "#32415a"        # list item hover
_BORDER_SOFT = "#2a3748"    # hairline card border / separator
_TEXT = "#e6edf3"
_TEXT_MUTED = "#8b97a7"
_TEXT_DISABLED = "#556274"
_ACCENT = "#f97316"          # warm orange — primary CTA + checkbox fill
_ACCENT_HOVER = "#fb923c"
_ACCENT_PRESSED = "#ea580c"
_ACCENT_EDGE = "#c2410c"     # darker lip under the CTA (pseudo-shadow)
_INFO = "#3b82f6"            # cool blue — reserved for informational accents
_ROW_ALT = "#243142"
_SELECT = _ACCENT


_STYLESHEET = f"""
/* =========================================================
   Base
   ========================================================= */
QMainWindow, QWidget#centralwidget {{
    background-color: {_BG_BASE};
    color: {_TEXT};
    font-family: "Segoe UI", "Inter", "Arial";
    font-size: 10pt;
}}
QWidget {{
    color: {_TEXT};
}}
QWidget#mainColumn, QWidget#rightPanel, QWidget#leftPanel {{
    background-color: {_BG_BASE};
    border: none;
}}
QLabel {{
    color: {_TEXT};
    background: transparent;
}}
QLabel:disabled {{
    color: {_TEXT_DISABLED};
}}
QLabel#heroTitle {{
    color: {_TEXT};
    font-size: 28pt;
    font-weight: 700;
    padding: 0;
    margin: 0;
}}
QLabel#heroSubtitle {{
    color: {_TEXT_MUTED};
    font-size: 10pt;
    padding: 0;
    margin: 0;
}}

/* =========================================================
   Sections: card-style QGroupBox with an orange floating title
   ========================================================= */
QGroupBox {{
    background-color: {_BG_CARD};
    border: 1px solid {_BORDER_SOFT};
    border-radius: 12px;
    margin-top: 14px;
    padding: 20px 20px 16px 20px;
    color: {_ACCENT};
    font-size: 10pt;
}}
QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    left: 18px;
    top: 2px;
    padding: 2px 10px;
    background-color: {_BG_BASE};
    color: {_ACCENT};
    font-weight: 500;
    font-size: 10pt;
}}

/* Thin divider between step cards in the left column */
QFrame#stepSeparator {{
    background-color: {_BORDER_SOFT};
    color: {_BORDER_SOFT};
    max-height: 1px;
    min-height: 1px;
    border: none;
}}

/* =========================================================
   Help "banner" reduced to a single-line text link
   ========================================================= */
QCommandLinkButton#helpButton {{
    background: transparent;
    border: none;
    color: {_TEXT_MUTED};
    text-align: left;
    padding: 2px 0;
    font-size: 9pt;
    text-decoration: underline;
}}
QCommandLinkButton#helpButton:hover {{
    color: {_TEXT};
}}

/* =========================================================
   Buttons — generic secondary / ghost / primary
   ========================================================= */
QPushButton {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid transparent;
    border-radius: 8px;
    padding: 6px 14px;
    min-height: 24px;
}}
QPushButton:hover {{
    background-color: {_BG_HOVER};
}}
QPushButton:pressed {{
    background-color: #263345;
}}
QPushButton:disabled {{
    background-color: #243142;
    color: {_TEXT_DISABLED};
}}

/* Primary call-to-action — bright orange "Rename" */
QPushButton#renameButton {{
    background-color: {_ACCENT};
    color: #ffffff;
    border: 1px solid {_ACCENT_EDGE};
    border-radius: 10px;
    padding: 0 22px;
    font-size: 10pt;
    font-weight: 600;
    min-height: 44px;
}}
QPushButton#renameButton:hover {{
    background-color: {_ACCENT_HOVER};
    border-color: {_ACCENT_EDGE};
}}
QPushButton#renameButton:pressed {{
    background-color: {_ACCENT_PRESSED};
}}
QPushButton#renameButton:disabled {{
    background-color: #6b3a1e;
    color: #cbbdb0;
    border-color: transparent;
}}

/* Folder picker — compact icon square */
QPushButton#openFolderButton {{
    background-color: {_BG_ELEVATED};
    border: 1px solid transparent;
    border-radius: 10px;
    padding: 0;
    min-width: 40px;
    min-height: 40px;
    max-width: 40px;
    max-height: 40px;
}}
QPushButton#openFolderButton:hover {{
    background-color: {_BG_HOVER};
}}

/* Specific-files icon buttons */
QPushButton#specificFilesAddButton,
QPushButton#specificFilesClearButton {{
    background-color: {_BG_ELEVATED};
    border: 1px solid transparent;
    border-radius: 8px;
    padding: 0;
    min-width: 32px;
    min-height: 32px;
    max-width: 32px;
    max-height: 32px;
}}
QPushButton#specificFilesAddButton:hover,
QPushButton#specificFilesClearButton:hover {{
    background-color: {_BG_HOVER};
}}
QPushButton#specificFilesAddButton:disabled,
QPushButton#specificFilesClearButton:disabled {{
    background-color: #243142;
}}

/* =========================================================
   Inputs — line edits, combos, spin boxes
   ========================================================= */
QLineEdit {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid transparent;
    border-radius: 8px;
    padding: 6px 10px;
    selection-background-color: {_ACCENT};
    selection-color: #ffffff;
    min-height: 24px;
}}
QLineEdit:focus {{
    border: 1px solid {_ACCENT};
    background-color: {_BG_ELEVATED};
}}
QLineEdit:disabled {{
    background-color: #243142;
    color: {_TEXT_DISABLED};
}}

QComboBox {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid transparent;
    border-radius: 8px;
    padding: 6px 12px;
    min-height: 24px;
}}
QComboBox:focus {{
    border: 1px solid {_ACCENT};
}}
QComboBox:disabled {{
    background-color: #243142;
    color: {_TEXT_DISABLED};
}}
QComboBox::drop-down {{
    border: none;
    width: 20px;
}}
QComboBox::down-arrow {{
    image: none;
    width: 0;
    height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 5px solid {_TEXT_MUTED};
    margin-right: 8px;
}}
QComboBox QAbstractItemView {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid {_BORDER_SOFT};
    border-radius: 6px;
    padding: 4px;
    selection-background-color: {_ACCENT};
    selection-color: #ffffff;
    outline: 0;
}}

QSpinBox {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid transparent;
    border-radius: 8px;
    padding: 6px 8px;
    min-height: 24px;
}}
QSpinBox:focus {{
    border: 1px solid {_ACCENT};
}}
QSpinBox:disabled {{
    background-color: #243142;
    color: {_TEXT_DISABLED};
}}
QSpinBox::up-button, QSpinBox::down-button {{
    background: transparent;
    border: none;
    width: 16px;
}}
QSpinBox::up-arrow {{
    image: none;
    width: 0; height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-bottom: 5px solid {_TEXT_MUTED};
}}
QSpinBox::down-arrow {{
    image: none;
    width: 0; height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 5px solid {_TEXT_MUTED};
}}

/* =========================================================
   Check boxes
   ========================================================= */
QCheckBox {{
    color: {_TEXT};
    spacing: 10px;
    padding: 3px 0;
    background: transparent;
}}
QCheckBox:disabled {{
    color: {_TEXT_DISABLED};
}}
QCheckBox::indicator {{
    width: 16px;
    height: 16px;
    border: 1px solid {_TEXT_DISABLED};
    border-radius: 4px;
    background: transparent;
}}
QCheckBox::indicator:hover {{
    border-color: {_ACCENT};
}}
QCheckBox::indicator:checked {{
    background-color: {_ACCENT};
    border-color: {_ACCENT};
    image: none;
}}
QCheckBox::indicator:checked:hover {{
    background-color: {_ACCENT_HOVER};
    border-color: {_ACCENT_HOVER};
}}
QCheckBox::indicator:disabled {{
    border-color: {_BORDER_SOFT};
    background: transparent;
}}

/* =========================================================
   List widgets (common + specific file filters)
   ========================================================= */
QListWidget {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid transparent;
    border-radius: 8px;
    padding: 4px;
    outline: 0;
}}
QListWidget::item {{
    padding: 6px 8px;
    border-radius: 6px;
}}
QListWidget::item:hover {{
    background-color: {_BG_HOVER};
}}
QListWidget::item:selected {{
    background-color: {_ACCENT};
    color: #ffffff;
}}
QListWidget:disabled {{
    background-color: #243142;
    color: {_TEXT_DISABLED};
}}

/* =========================================================
   Preview table — maximal minimalism
   ========================================================= */
QTableWidget#filesList {{
    background-color: transparent;
    alternate-background-color: {_ROW_ALT};
    color: {_TEXT};
    gridline-color: transparent;
    border: none;
    selection-background-color: {_ACCENT};
    selection-color: #ffffff;
    outline: 0;
}}
QTableWidget#filesList::item {{
    padding: 6px 8px;
    border: none;
}}
QTableWidget#filesList::item:hover {{
    background-color: {_BG_ELEVATED};
}}
QHeaderView {{
    background: transparent;
    border: none;
}}
QHeaderView::section {{
    background-color: transparent;
    color: {_TEXT_MUTED};
    padding: 10px 8px 8px 8px;
    border: none;
    border-bottom: 1px solid {_BORDER_SOFT};
    font-size: 9pt;
    font-weight: 600;
}}
QTableCornerButton::section {{
    background: transparent;
    border: none;
    border-bottom: 1px solid {_BORDER_SOFT};
}}

/* =========================================================
   Status bar + progress bar
   ========================================================= */
QStatusBar {{
    background: transparent;
    color: {_TEXT_MUTED};
    border: none;
    padding: 4px 16px;
    font-size: 9pt;
}}
QStatusBar::item {{
    border: none;
}}
QProgressBar {{
    background-color: {_BG_ELEVATED};
    color: transparent;
    border: none;
    border-radius: 3px;
    max-height: 6px;
    min-height: 6px;
    text-align: center;
}}
QProgressBar::chunk {{
    background-color: {_ACCENT};
    border-radius: 3px;
}}

/* =========================================================
   Menu bar / menus — very quiet
   ========================================================= */
QMenuBar {{
    background: transparent;
    color: {_TEXT_MUTED};
    border: none;
    padding: 10px 40px;
    font-size: 10pt;
}}
QMenuBar::item {{
    background: transparent;
    padding: 8px 18px;
    border-radius: 4px;
}}
QMenuBar::item:selected {{
    background: transparent;
    color: {_ACCENT};
}}
QMenuBar::item:pressed {{
    background: transparent;
    color: {_ACCENT_PRESSED};
}}
QMenu {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid {_BORDER_SOFT};
    border-radius: 6px;
    padding: 6px;
}}
QMenu::item {{
    padding: 6px 20px;
    border-radius: 4px;
}}
QMenu::item:selected {{
    background-color: {_ACCENT};
    color: #ffffff;
}}
QMenu::separator {{
    height: 1px;
    background: {_BORDER_SOFT};
    margin: 4px 8px;
}}

/* =========================================================
   Separator frame (kept for backwards compat; now invisible)
   ========================================================= */
QFrame#separator {{
    background-color: transparent;
    color: transparent;
    max-height: 1px;
    border: none;
}}

/* =========================================================
   Scroll areas & scroll bars — 8px thin
   ========================================================= */
QScrollArea {{
    background: transparent;
    border: none;
}}
QScrollArea > QWidget > QWidget {{
    background: transparent;
}}
QScrollBar:vertical {{
    background: transparent;
    width: 8px;
    margin: 0;
    border: none;
}}
QScrollBar::handle:vertical {{
    background: {_BORDER_SOFT};
    border-radius: 4px;
    min-height: 24px;
    margin: 2px;
}}
QScrollBar::handle:vertical:hover {{
    background: {_TEXT_DISABLED};
}}
QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0;
    background: none;
}}
QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {{
    background: none;
}}
QScrollBar:horizontal {{
    background: transparent;
    height: 8px;
    margin: 0;
    border: none;
}}
QScrollBar::handle:horizontal {{
    background: {_BORDER_SOFT};
    border-radius: 4px;
    min-width: 24px;
    margin: 2px;
}}
QScrollBar::handle:horizontal:hover {{
    background: {_TEXT_DISABLED};
}}
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0;
    background: none;
}}
QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{
    background: none;
}}

/* =========================================================
   Splitter — invisible 1px handle
   ========================================================= */
QSplitter::handle {{
    background: transparent;
}}
QSplitter::handle:horizontal {{
    width: 1px;
}}
QSplitter::handle:horizontal:hover {{
    background: {_BORDER_SOFT};
}}

/* =========================================================
   Tooltip + validation label
   ========================================================= */
QToolTip {{
    background-color: {_BG_ELEVATED};
    color: {_TEXT};
    border: 1px solid {_BORDER_SOFT};
    padding: 4px 8px;
    border-radius: 4px;
}}
QLabel#invalidLabel {{
    color: {_ACCENT};
    font-style: italic;
    font-size: 9pt;
}}
"""


class Ui_MainWindow(object):
    """UI setup for the main window.

    Public contract: every ``self.*`` widget and ``setObjectName`` value used
    here is referenced by name in ``main_window.py`` and ``ui_translator.py``.
    """

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setMinimumSize(QSize(980, 620))

        base_font = QFont("Segoe UI", 10)
        MainWindow.setFont(base_font)
        MainWindow.setStyleSheet(_STYLESHEET)

        self._create_actions(MainWindow)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        # The central widget IS the content column now — no sidebar wrapper.
        content_layout = QVBoxLayout(self.centralwidget)
        content_layout.setContentsMargins(48, 0, 48, 32)
        content_layout.setSpacing(0)

        self._build_hero(self.centralwidget, content_layout)

        splitter = QSplitter(Qt.Horizontal, self.centralwidget)
        splitter.setObjectName(u"mainSplitter")
        splitter.setChildrenCollapsible(False)
        splitter.setHandleWidth(1)
        content_layout.addWidget(splitter, 1)

        # Left column: scrolling stack of section cards.
        left_scroll = QScrollArea(splitter)
        left_scroll.setObjectName(u"leftScroll")
        left_scroll.setWidgetResizable(True)
        left_scroll.setFrameShape(QFrame.NoFrame)
        left_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        left_panel = QWidget()
        left_panel.setObjectName(u"leftPanel")
        left_layout = QVBoxLayout(left_panel)
        left_layout.setContentsMargins(0, 0, 20, 12)
        left_layout.setSpacing(0)
        left_scroll.setWidget(left_panel)

        self._build_step1(left_panel, left_layout)
        self._add_step_separator(left_panel, left_layout)
        self._build_step2(left_panel, left_layout)
        self._add_step_separator(left_panel, left_layout)
        self._build_step3(left_panel, left_layout)
        self._add_step_separator(left_panel, left_layout)
        self._build_step4(left_panel, left_layout)
        self._add_step_separator(left_panel, left_layout)
        self._build_step5(left_panel, left_layout)
        left_layout.addStretch(1)

        # Right column: the preview table.
        right_panel = QWidget(splitter)
        right_panel.setObjectName(u"rightPanel")
        right_layout = QVBoxLayout(right_panel)
        right_layout.setContentsMargins(20, 0, 0, 0)
        right_layout.setSpacing(0)
        self._build_files_table(right_panel, right_layout)

        splitter.addWidget(left_scroll)
        splitter.addWidget(right_panel)
        splitter.setStretchFactor(0, 55)
        splitter.setStretchFactor(1, 45)
        splitter.setSizes([640, 500])
        left_scroll.setMinimumWidth(460)
        right_panel.setMinimumWidth(380)

        MainWindow.setCentralWidget(self.centralwidget)

        self._build_menu_and_status(MainWindow)
        self._set_tab_order()

        self.retranslateUi(MainWindow)

        self.inneCombo.setCurrentIndex(0)
        self.rulesCombo.setCurrentIndex(1)

        QMetaObject.connectSlotsByName(MainWindow)

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------
    def _create_actions(self, MainWindow):
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setChecked(False)
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionPortugues_BR = QAction(MainWindow)
        self.actionPortugues_BR.setObjectName(u"actionPortugues_BR")
        self.actionPortugues_BR.setCheckable(True)
        self.actionAlways_backup_before_renaming = QAction(MainWindow)
        self.actionAlways_backup_before_renaming.setObjectName(
            u"actionAlways_backup_before_renaming"
        )
        self.actionAlways_backup_before_renaming.setCheckable(True)
        self.actionProtect_Paths = QAction(MainWindow)
        self.actionProtect_Paths.setObjectName(u"actionProtect_Paths")
        self.actionProtect_Paths.setCheckable(True)
        self.actionProtect_Paths.setChecked(True)
        self.actionOpen_Folder = QAction(MainWindow)
        self.actionOpen_Folder.setObjectName(u"actionOpen_Folder")
        self.actionOpen_settings = QAction(MainWindow)
        self.actionOpen_settings.setObjectName(u"actionOpen_settings")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actiontest = QAction(MainWindow)
        self.actiontest.setObjectName(u"actiontest")

    # ------------------------------------------------------------------
    # Step separator — thin hairline between step cards in the left column
    # ------------------------------------------------------------------
    def _add_step_separator(self, parent, layout):
        # Pure layout decoration: not stored on ``self`` so nothing external
        # depends on these widgets.
        separator = QFrame(parent)
        separator.setObjectName(u"stepSeparator")
        separator.setFrameShape(QFrame.HLine)
        separator.setFrameShadow(QFrame.Plain)
        container = QWidget(parent)
        container_layout = QVBoxLayout(container)
        container_layout.setContentsMargins(0, 6, 0, 6)
        container_layout.setSpacing(0)
        container_layout.addWidget(separator)
        layout.addWidget(container)

    # ------------------------------------------------------------------
    # Hero + quiet help link
    # ------------------------------------------------------------------
    def _build_hero(self, parent, layout):
        self.heroTitle = QLabel(parent)
        self.heroTitle.setObjectName(u"heroTitle")
        self.heroTitle.setText("Rename files")
        self.heroTitle.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        layout.addWidget(self.heroTitle)

        layout.addSpacing(4)

        self.heroSubtitle = QLabel(parent)
        self.heroSubtitle.setObjectName(u"heroSubtitle")
        self.heroSubtitle.setText("Select a folder, choose a rule, preview and apply.")
        self.heroSubtitle.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        layout.addWidget(self.heroSubtitle)

        self.helpButton = QCommandLinkButton(parent)
        self.helpButton.setObjectName(u"helpButton")
        # Flatten the command-link visuals: no arrow icon, no description.
        self.helpButton.setIcon(QIcon())
        self.helpButton.setDescription("")
        self.helpButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.helpButton.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        layout.addSpacing(8)
        layout.addWidget(self.helpButton)

    # ------------------------------------------------------------------
    # Step 1: folder picker
    # ------------------------------------------------------------------
    def _build_step1(self, parent, parent_layout):
        self.Step1 = QGroupBox(parent)
        self.Step1.setObjectName(u"Step1")
        self.Step1.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        self.horizontalLayout_2 = QHBoxLayout(self.Step1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setSpacing(12)

        # Row: folder-picker button + path field.
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setSpacing(10)

        self.openFolderButton = QPushButton(self.Step1)
        self.openFolderButton.setObjectName(u"openFolderButton")
        self.openFolderButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.openFolderButton.setIconSize(QSize(18, 18))
        # Preserve the Designer theme-icon fallback verbatim.
        icon = QIcon()
        theme_name = u"Segoe UI,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
        if QIcon.hasThemeIcon(theme_name):
            icon = QIcon.fromTheme(theme_name)
        else:
            icon.addFile(u"../Lite/gui/img/open-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.openFolderButton.setIcon(icon)
        self.horizontalLayout_5.addWidget(self.openFolderButton)

        self.pathLine = QLineEdit(self.Step1)
        self.pathLine.setObjectName(u"pathLine")
        self.pathLine.setEnabled(False)
        self.pathLine.setMinimumHeight(36)
        self.pathLine.setPlaceholderText("No folder selected")
        self.horizontalLayout_5.addWidget(self.pathLine)

        self.verticalLayout_3.addLayout(self.horizontalLayout_5)

        self.includeFoldersCheckbox = QCheckBox(self.Step1)
        self.includeFoldersCheckbox.setObjectName(u"includeFoldersCheckbox")
        self.verticalLayout_3.addWidget(self.includeFoldersCheckbox)

        self.includeSubdirCheckbox = QCheckBox(self.Step1)
        self.includeSubdirCheckbox.setObjectName(u"includeSubdirCheckbox")
        self.verticalLayout_3.addWidget(self.includeSubdirCheckbox)

        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        parent_layout.addWidget(self.Step1)

    # ------------------------------------------------------------------
    # Step 2: file-type filters
    # ------------------------------------------------------------------
    def _build_step2(self, parent, parent_layout):
        self.Step2 = QGroupBox(parent)
        self.Step2.setObjectName(u"Step2")
        self.Step2.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)

        self.horizontalLayout_3 = QHBoxLayout(self.Step2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(16)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSpacing(12)

        self.allFilesCheckbox = QCheckBox(self.Step2)
        self.allFilesCheckbox.setObjectName(u"allFilesCheckbox")
        self.allFilesCheckbox.setCursor(QCursor(Qt.ArrowCursor))
        self.allFilesCheckbox.setChecked(True)
        self.verticalLayout.addWidget(self.allFilesCheckbox)

        self.commonFilesCheckbox = QCheckBox(self.Step2)
        self.commonFilesCheckbox.setObjectName(u"commonFilesCheckbox")
        self.commonFilesCheckbox.setCursor(QCursor(Qt.ArrowCursor))
        self.commonFilesCheckbox.setCheckable(True)
        self.commonFilesCheckbox.setChecked(False)
        self.commonFilesCheckbox.setAutoExclusive(False)
        self.verticalLayout.addWidget(self.commonFilesCheckbox)

        self.commonFilesList = QListWidget(self.Step2)
        self.commonFilesList.setObjectName(u"commonFilesList")
        self.commonFilesList.setEnabled(False)
        self.commonFilesList.setMinimumHeight(120)
        self.commonFilesList.setSelectionMode(QAbstractItemView.MultiSelection)
        self.commonFilesList.setSpacing(1)
        self.commonFilesList.setViewMode(QListView.ListMode)
        self.commonFilesList.setUniformItemSizes(False)
        self.commonFilesList.setWordWrap(False)
        self.commonFilesList.setSelectionRectVisible(True)
        self.verticalLayout.addWidget(self.commonFilesList)

        self.horizontalLayout_3.addLayout(self.verticalLayout, 1)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setVerticalSpacing(12)

        self.specificFilesCheckbox = QCheckBox(self.Step2)
        self.specificFilesCheckbox.setObjectName(u"specificFilesCheckbox")
        self.specificFilesCheckbox.setCursor(QCursor(Qt.ArrowCursor))
        self.gridLayout.addWidget(self.specificFilesCheckbox, 0, 0, 1, 2)

        self.specificFilesLine = QLineEdit(self.Step2)
        self.specificFilesLine.setObjectName(u"specificFilesLine")
        self.specificFilesLine.setEnabled(False)
        self.specificFilesLine.setMinimumHeight(36)
        self.gridLayout.addWidget(self.specificFilesLine, 1, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSpacing(6)

        self.specificFilesAddButton = QPushButton(self.Step2)
        self.specificFilesAddButton.setObjectName(u"specificFilesAddButton")
        self.specificFilesAddButton.setEnabled(False)
        self.specificFilesAddButton.setIconSize(QSize(16, 16))
        self.specificFilesAddButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.specificFilesAddButton)

        self.specificFilesClearButton = QPushButton(self.Step2)
        self.specificFilesClearButton.setObjectName(u"specificFilesClearButton")
        self.specificFilesClearButton.setEnabled(False)
        self.specificFilesClearButton.setIconSize(QSize(16, 16))
        self.specificFilesClearButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.specificFilesClearButton)

        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.specificFilesList = QListWidget(self.Step2)
        self.specificFilesList.setObjectName(u"specificFilesList")
        self.specificFilesList.setEnabled(False)
        self.specificFilesList.setMinimumHeight(120)
        self.specificFilesList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.specificFilesList.setProperty("showDropIndicator", False)
        self.specificFilesList.setSelectionMode(QAbstractItemView.NoSelection)
        self.specificFilesList.setResizeMode(QListView.Fixed)
        self.specificFilesList.setSpacing(1)
        self.specificFilesList.setViewMode(QListView.ListMode)
        self.specificFilesList.setUniformItemSizes(False)
        self.specificFilesList.setWordWrap(False)
        self.specificFilesList.setSelectionRectVisible(True)
        self.gridLayout.addWidget(self.specificFilesList, 2, 0, 1, 2)

        self.horizontalLayout_3.addLayout(self.gridLayout, 1)
        parent_layout.addWidget(self.Step2)

    # ------------------------------------------------------------------
    # Step 3: rule combo + sequential spinners
    # ------------------------------------------------------------------
    def _build_step3(self, parent, parent_layout):
        self.Step30 = QGroupBox(parent)
        self.Step30.setObjectName(u"Step30")
        self.Step30.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        outer = QVBoxLayout(self.Step30)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.setSpacing(12)

        # ``self.Step3`` remains a QLabel — ``UiTranslator`` drives its text.
        self.Step3 = QLabel(self.Step30)
        self.Step3.setObjectName(u"Step3")
        self.Step3.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.Step3.setStyleSheet(
            "color: " + _TEXT_MUTED + "; font-weight: 600; font-size: 10pt;"
        )
        self.Step3.setVisible(False)  # header handled by QGroupBox title

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setSpacing(10)

        self.rulesCombo = QComboBox(self.Step30)
        self.rulesCombo.addItem("")
        self.rulesCombo.addItem("")
        self.rulesCombo.addItem("")
        self.rulesCombo.addItem("")
        self.rulesCombo.setObjectName(u"rulesCombo")
        self.rulesCombo.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.rulesCombo.setMinimumHeight(36)
        self.rulesCombo.setModelColumn(0)
        self.horizontalLayout_11.addWidget(self.rulesCombo, 2)

        self.startLabel = QLabel(self.Step30)
        self.startLabel.setObjectName(u"startLabel")
        self.startLabel.setStyleSheet("color: " + _TEXT_MUTED + ";")
        self.horizontalLayout_11.addWidget(self.startLabel)

        self.startSpin = QSpinBox(self.Step30)
        self.startSpin.setObjectName(u"startSpin")
        self.startSpin.setEnabled(False)
        self.startSpin.setMinimumHeight(36)
        self.startSpin.setMinimumWidth(76)
        self.horizontalLayout_11.addWidget(self.startSpin)

        self.countLabel = QLabel(self.Step30)
        self.countLabel.setObjectName(u"countLabel")
        self.countLabel.setStyleSheet("color: " + _TEXT_MUTED + ";")
        self.horizontalLayout_11.addWidget(self.countLabel)

        self.countSpin = QSpinBox(self.Step30)
        self.countSpin.setObjectName(u"countSpin")
        self.countSpin.setEnabled(False)
        self.countSpin.setWrapping(False)
        self.countSpin.setMinimum(1)
        self.countSpin.setMinimumHeight(36)
        self.countSpin.setMinimumWidth(76)
        self.horizontalLayout_11.addWidget(self.countSpin)

        outer.addWidget(self.Step3)
        outer.addLayout(self.horizontalLayout_11)
        parent_layout.addWidget(self.Step30)

    # ------------------------------------------------------------------
    # Step 4: find / replace / flags
    # ------------------------------------------------------------------
    def _build_step4(self, parent, parent_layout):
        self.Step4 = QGroupBox(parent)
        self.Step4.setObjectName(u"Step4")
        self.Step4.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        self.gridLayout_5 = QGridLayout(self.Step4)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(12)
        self.gridLayout_5.setVerticalSpacing(12)

        label_policy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)

        # Row 0: Find / Case sensitive.
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setSpacing(10)

        self.findLabel = QLabel(self.Step4)
        self.findLabel.setObjectName(u"findLabel")
        self.findLabel.setSizePolicy(label_policy)
        self.findLabel.setMinimumWidth(120)
        self.findLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.findLabel.setStyleSheet("color: " + _TEXT_MUTED + ";")
        self.horizontalLayout_6.addWidget(self.findLabel)

        self.findLine = QLineEdit(self.Step4)
        self.findLine.setObjectName(u"findLine")
        self.findLine.setMinimumHeight(36)
        self.findLine.setFocusPolicy(Qt.ClickFocus)
        self.findLine.setLayoutDirection(Qt.LeftToRight)
        self.findLine.setClearButtonEnabled(True)
        self.horizontalLayout_6.addWidget(self.findLine)

        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)

        self.caseSentitiveCheckbox = QCheckBox(self.Step4)
        self.caseSentitiveCheckbox.setObjectName(u"caseSentitiveCheckbox")
        self.caseSentitiveCheckbox.setChecked(True)
        self.gridLayout_5.addWidget(self.caseSentitiveCheckbox, 0, 1, 1, 1)

        # Row 1: invalid label / Regex.
        self.invalidLabel = QLabel(self.Step4)
        self.invalidLabel.setObjectName(u"invalidLabel")
        self.invalidLabel.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.gridLayout_5.addWidget(self.invalidLabel, 1, 0, 1, 1)

        self.regexCheckbox = QCheckBox(self.Step4)
        self.regexCheckbox.setObjectName(u"regexCheckbox")
        self.gridLayout_5.addWidget(self.regexCheckbox, 1, 1, 1, 1)

        # Row 2: replace / in+combo.
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setSpacing(10)

        self.replaceLabel = QLabel(self.Step4)
        self.replaceLabel.setObjectName(u"replaceLabel")
        self.replaceLabel.setSizePolicy(label_policy)
        self.replaceLabel.setMinimumWidth(120)
        self.replaceLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.replaceLabel.setStyleSheet("color: " + _TEXT_MUTED + ";")
        self.horizontalLayout_4.addWidget(self.replaceLabel)

        self.replaceLine = QLineEdit(self.Step4)
        self.replaceLine.setObjectName(u"replaceLine")
        self.replaceLine.setMinimumHeight(36)
        self.replaceLine.setFocusPolicy(Qt.ClickFocus)
        self.replaceLine.setClearButtonEnabled(True)
        self.horizontalLayout_4.addWidget(self.replaceLine)

        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setSpacing(10)

        self.inLabel = QLabel(self.Step4)
        self.inLabel.setObjectName(u"inLabel")
        self.inLabel.setSizePolicy(label_policy)
        self.inLabel.setStyleSheet("color: " + _TEXT_MUTED + ";")
        self.horizontalLayout_8.addWidget(self.inLabel)

        self.inneCombo = QComboBox(self.Step4)
        self.inneCombo.addItem("")
        self.inneCombo.addItem("")
        self.inneCombo.setObjectName(u"inneCombo")
        self.inneCombo.setEnabled(False)
        self.inneCombo.setMinimumHeight(36)
        self.horizontalLayout_8.addWidget(self.inneCombo, 1)

        self.gridLayout_5.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)

        self.gridLayout_5.setColumnStretch(0, 3)
        self.gridLayout_5.setColumnStretch(1, 2)

        parent_layout.addWidget(self.Step4)

    # ------------------------------------------------------------------
    # Step 5: backup + rename/exit
    # ------------------------------------------------------------------
    def _build_step5(self, parent, parent_layout):
        # Wrap Step 5 in a card like the other steps so the orange "Step 5:"
        # title sits on the card border. ``Step50`` remains a QVBoxLayout for
        # backwards compatibility with any callers/tests.
        self.Step5Box = QGroupBox(parent)
        self.Step5Box.setObjectName(u"Step5Box")
        self.Step5Box.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        self.Step50 = QVBoxLayout(self.Step5Box)
        self.Step50.setObjectName(u"Step50")
        self.Step50.setSpacing(12)
        self.Step50.setContentsMargins(0, 0, 0, 0)

        self.backupCheckbox = QCheckBox(self.Step5Box)
        self.backupCheckbox.setObjectName(u"backupCheckbox")
        self.Step50.addWidget(self.backupCheckbox)

        self.separator = QFrame(self.Step5Box)
        self.separator.setObjectName(u"separator")
        self.separator.setFrameShape(QFrame.NoFrame)
        self.separator.setFrameShadow(QFrame.Plain)
        self.separator.setFixedHeight(0)
        self.Step50.addWidget(self.separator)

        self.Step5 = QLabel(self.Step5Box)
        self.Step5.setObjectName(u"Step5")
        self.Step5.setStyleSheet(
            "color: " + _TEXT_MUTED + "; font-weight: 600; font-size: 10pt;"
        )
        self.Step5.setVisible(False)  # the QGroupBox title already carries "Step 5: …"
        self.Step50.addWidget(self.Step5)

        self.Buttons = QHBoxLayout()
        self.Buttons.setObjectName(u"Buttons")
        self.Buttons.setSpacing(10)

        self.renameButton = QPushButton(self.Step5Box)
        self.renameButton.setObjectName(u"renameButton")
        self.renameButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.renameButton.setDefault(True)
        self.renameButton.setAutoDefault(True)
        self.Buttons.addWidget(self.renameButton, 2)

        self.Step50.addLayout(self.Buttons)

        parent_layout.addWidget(self.Step5Box)

    # ------------------------------------------------------------------
    # Preview table
    # ------------------------------------------------------------------
    def _build_files_table(self, parent, parent_layout):
        self.Frame = QVBoxLayout()
        self.Frame.setObjectName(u"Frame")
        self.Frame.setContentsMargins(0, 0, 0, 0)
        self.Frame.setSpacing(0)

        self.filesList = QTableWidget(parent)
        self.filesList.setObjectName(u"filesList")
        if self.filesList.columnCount() < 5:
            self.filesList.setColumnCount(5)
        for column in range(5):
            self.filesList.setHorizontalHeaderItem(column, QTableWidgetItem())

        self.filesList.setEnabled(True)
        self.filesList.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.filesList.setFrameShape(QFrame.NoFrame)
        self.filesList.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.filesList.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.filesList.setAutoScroll(True)
        self.filesList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.filesList.setTabKeyNavigation(False)
        self.filesList.setProperty("showDropIndicator", False)
        self.filesList.setDragDropOverwriteMode(False)
        self.filesList.setAlternatingRowColors(True)
        self.filesList.setSelectionMode(QAbstractItemView.NoSelection)
        self.filesList.setTextElideMode(Qt.ElideMiddle)
        self.filesList.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.filesList.setShowGrid(False)
        self.filesList.setGridStyle(Qt.SolidLine)
        self.filesList.setSortingEnabled(True)
        self.filesList.setWordWrap(False)
        self.filesList.setCornerButtonEnabled(True)
        self.filesList.setRowCount(0)
        self.filesList.setColumnCount(5)

        header = self.filesList.horizontalHeader()
        header.setVisible(True)
        header.setCascadingSectionResizes(True)
        header.setMinimumSectionSize(80)
        header.setDefaultSectionSize(140)
        header.setHighlightSections(False)
        header.setStretchLastSection(True)
        header.setSectionResizeMode(QHeaderView.Interactive)
        header.resizeSection(0, 200)  # File name
        header.resizeSection(1, 200)  # New file name
        header.resizeSection(2, 100)  # Extension
        header.resizeSection(3, 180)  # Path
        header.resizeSection(4, 90)   # Size

        vheader = self.filesList.verticalHeader()
        vheader.setVisible(False)
        vheader.setCascadingSectionResizes(False)
        vheader.setMinimumSectionSize(28)
        vheader.setDefaultSectionSize(32)
        vheader.setHighlightSections(False)
        vheader.setProperty("showSortIndicator", False)
        vheader.setStretchLastSection(False)

        self.Frame.addWidget(self.filesList)
        parent_layout.addLayout(self.Frame)

    # ------------------------------------------------------------------
    # Menu bar + status bar
    # ------------------------------------------------------------------
    def _build_menu_and_status(self, MainWindow):
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusBar)

        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1200, 28))
        self.menuBar.setNativeMenuBar(False)
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuOptions = QMenu(self.menuBar)
        self.menuOptions.setObjectName(u"menuOptions")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAlways_backup_before_renaming)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionProtect_Paths)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionOpen_settings)

    # ------------------------------------------------------------------
    # Keyboard navigation
    # ------------------------------------------------------------------
    def _set_tab_order(self):
        QWidget.setTabOrder(self.helpButton, self.openFolderButton)
        QWidget.setTabOrder(self.openFolderButton, self.pathLine)
        QWidget.setTabOrder(self.pathLine, self.includeFoldersCheckbox)
        QWidget.setTabOrder(self.includeFoldersCheckbox, self.includeSubdirCheckbox)
        QWidget.setTabOrder(self.includeSubdirCheckbox, self.allFilesCheckbox)
        QWidget.setTabOrder(self.allFilesCheckbox, self.commonFilesCheckbox)
        QWidget.setTabOrder(self.commonFilesCheckbox, self.commonFilesList)
        QWidget.setTabOrder(self.commonFilesList, self.specificFilesCheckbox)
        QWidget.setTabOrder(self.specificFilesCheckbox, self.specificFilesLine)
        QWidget.setTabOrder(self.specificFilesLine, self.specificFilesAddButton)
        QWidget.setTabOrder(self.specificFilesAddButton, self.specificFilesClearButton)
        QWidget.setTabOrder(self.specificFilesClearButton, self.specificFilesList)
        QWidget.setTabOrder(self.specificFilesList, self.rulesCombo)
        QWidget.setTabOrder(self.rulesCombo, self.startSpin)
        QWidget.setTabOrder(self.startSpin, self.countSpin)
        QWidget.setTabOrder(self.countSpin, self.findLine)
        QWidget.setTabOrder(self.findLine, self.caseSentitiveCheckbox)
        QWidget.setTabOrder(self.caseSentitiveCheckbox, self.regexCheckbox)
        QWidget.setTabOrder(self.regexCheckbox, self.replaceLine)
        QWidget.setTabOrder(self.replaceLine, self.inneCombo)
        QWidget.setTabOrder(self.inneCombo, self.backupCheckbox)
        QWidget.setTabOrder(self.backupCheckbox, self.renameButton)
        QWidget.setTabOrder(self.renameButton, self.filesList)

    # ------------------------------------------------------------------
    # Translatable strings — source strings here are the i18n keys consumed
    # by ``package.views.ui_translator.UiTranslator`` and must stay in sync
    # with ``package/lang/bases/*.json``. Do not simplify.
    # ------------------------------------------------------------------
    def retranslateUi(self, MainWindow):
        tr = QCoreApplication.translate
        MainWindow.setWindowTitle(tr("MainWindow", u"MainWindow", None))

        self.actionExit.setText(tr("MainWindow", u"Exit", None))
        self.actionEnglish.setText(tr("MainWindow", u"English (en)", None))
        self.actionDocumentation.setText(tr("MainWindow", u"Documentation", None))
        self.actionPortugues_BR.setText(tr("MainWindow", u"Portuguese (pt_BR)", None))
        self.actionAlways_backup_before_renaming.setText(
            tr("MainWindow", u"Always backup before renaming", None)
        )
        self.actionProtect_Paths.setText(tr("MainWindow", u"Protect paths", None))
        self.actionOpen_Folder.setText(tr("MainWindow", u"Open Folder", None))
        self.actionOpen_settings.setText(tr("MainWindow", u"Settings", None))
        self.actionAbout.setText(tr("MainWindow", u"About", None))
        self.actiontest.setText(tr("MainWindow", u"test", None))

        self.Step4.setTitle(tr("MainWindow", u"Step 4: Choose some options", None))
        self.replaceLabel.setText(tr("MainWindow", u"... and replace with", None))
        self.inLabel.setText(tr("MainWindow", u"in", None))
        self.inneCombo.setItemText(0, tr("MainWindow", u"Before", None))
        self.inneCombo.setItemText(1, tr("MainWindow", u"After", None))
        self.findLabel.setText(tr("MainWindow", u"Find...", None))
        self.caseSentitiveCheckbox.setText(tr("MainWindow", u"Case Sensitive", None))
        self.regexCheckbox.setText(tr("MainWindow", u"Regular Expression", None))
        self.invalidLabel.setText("")

        self.helpButton.setText(
            tr("MainWindow", u"Need help? Click me!", None)
        )

        self.Step30.setTitle(tr("MainWindow", u"Step 3: Set the rules ", None))
        self.Step3.setText(tr("MainWindow", u"Step 3: Set the rules ", None))
        self.rulesCombo.setItemText(0, tr("MainWindow", u"Add Text or Date", None))
        self.rulesCombo.setItemText(1, tr("MainWindow", u"Replace File Name", None))
        self.rulesCombo.setItemText(2, tr("MainWindow", u"Replace File Extension", None))
        self.rulesCombo.setItemText(3, tr("MainWindow", u"Make sequential", None))
        self.startLabel.setText(tr("MainWindow", u"Start at", None))
        self.countLabel.setText(tr("MainWindow", u"Count by", None))

        self.Step1.setTitle(
            tr("MainWindow", u"Step 1: Select the folder where the files are located", None)
        )
        self.openFolderButton.setText("")
        self.includeFoldersCheckbox.setText(tr("MainWindow", u"Include folders", None))
        self.includeSubdirCheckbox.setText(
            tr("MainWindow", u"Include files in subdirectories", None)
        )

        self.backupCheckbox.setText(tr("MainWindow", u"Backup files before renaming", None))
        self.Step5.setText(tr("MainWindow", u"Step 5: Rename them", None))
        self.Step5Box.setTitle(tr("MainWindow", u"Step 5: Rename them", None))
        self.renameButton.setText(tr("MainWindow", u"Rename", None))

        self.Step2.setTitle(
            tr("MainWindow", u"Step 2: Select the types of files to rename", None)
        )
        self.allFilesCheckbox.setText(tr("MainWindow", u"All types of files", None))
        self.commonFilesCheckbox.setText(tr("MainWindow", u"Common types of files:", None))
        self.specificFilesCheckbox.setText(tr("MainWindow", u"Specific types of files:", None))
        self.specificFilesLine.setText("")
        self.specificFilesLine.setPlaceholderText(tr("MainWindow", u"Ex: mkv", None))
        self.specificFilesAddButton.setText("")
        self.specificFilesClearButton.setText("")

        self.filesList.horizontalHeaderItem(0).setText(
            tr("MainWindow", u"File name", None)
        )
        self.filesList.horizontalHeaderItem(1).setText(
            tr("MainWindow", u"New file name", None)
        )
        self.filesList.horizontalHeaderItem(2).setText(
            tr("MainWindow", u"Extension", None)
        )
        self.filesList.horizontalHeaderItem(3).setText(
            tr("MainWindow", u"Path", None)
        )
        self.filesList.horizontalHeaderItem(4).setText(
            tr("MainWindow", u"Size", None)
        )
        # Size column reads better right-aligned.
        self.filesList.horizontalHeaderItem(4).setTextAlignment(
            Qt.AlignRight | Qt.AlignVCenter
        )

        self.menuFile.setTitle(tr("MainWindow", u"File", None))
        self.menuHelp.setTitle(tr("MainWindow", u"Help", None))
        self.menuOptions.setTitle(tr("MainWindow", u"Options", None))
